create table if not exists evaluation
(
    id              bigint generated by default as identity not null,
    mutants         bigint                                  not null,
    covered_mutants bigint                                  not null,
    killed_mutants  bigint                                  not null,
    line_coverage   double                                  not null,
    branch_coverage double                                  not null,
    real_bug_result varchar(14),
    constraint ck_evaluation_real_bug_result check (real_bug_result in ('NOT_APPLICABLE', 'DETECTED', 'UNDETECTED')),
    constraint pk_evaluation primary key (id)
);

create table if not exists feedback_loop
(
    id                bigint generated by default as identity not null,
    target_id         bigint                                  not null,
    type              varchar(8),
    error_stack_trace text,
    success           boolean default false                   not null,
    created_at        timestamp                               not null,
    completed_at      timestamp,
    constraint ck_feedback_loop_type check (type in ('COVERAGE', 'MUTATION')),
    constraint pk_feedback_loop primary key (id)
);

create table if not exists feedback_loop_iteration
(
    id               bigint generated by default as identity not null,
    feedback_loop_id bigint                                  not null,
    iteration_id     bigint                                  not null,
    constraint pk_feedback_loop_iteration primary key (id)
);

create table if not exists fixer_stage
(
    id                  bigint generated by default as identity not null,
    iteration_id        bigint                                  not null,
    number              integer                                 not null,
    type                varchar(7)                              not null,
    success             boolean default false                   not null,
    follow_up_prompt_id bigint,
    error_message       text,
    created_at          timestamp                               not null,
    completed_at        timestamp,
    constraint ck_fixer_stage_type check (type in ('PARSE', 'COMPILE', 'TEST')),
    constraint uq_fixer_stage_follow_up_prompt_id unique (follow_up_prompt_id),
    constraint pk_fixer_stage primary key (id)
);

create table if not exists iteration
(
    id                   bigint generated by default as identity not null,
    target_id            bigint                                  not null,
    number               integer                                 not null,
    generation_prompt_id bigint,
    evaluation_id        bigint,
    created_at           timestamp                               not null,
    completed_at         timestamp,
    constraint pk_iteration primary key (id)
);

create table if not exists prompt
(
    id               bigint generated by default as identity not null,
    uuid             uuid,
    motive           varchar(8)                              not null,
    input_tokens     bigint,
    output_tokens    bigint,
    reasoning_tokens bigint,
    created_at       timestamp                               not null,
    completed_at     timestamp,
    constraint ck_prompt_motive check (motive in ('INITIAL', 'FIX', 'FEEDBACK')),
    constraint pk_prompt primary key (id)
);

create table if not exists prompt_message
(
    id        bigint generated by default as identity not null,
    prompt_id bigint                                  not null,
    text      text                                    not null,
    role      varchar(9)                              not null,
    constraint ck_prompt_message_role check (role in ('SYSTEM', 'USER', 'ASSISTANT')),
    constraint pk_prompt_message primary key (id)
);

create table if not exists run
(
    id                  bigint generated by default as identity not null,
    uuid                uuid                                    not null,
    d4j_project         varchar(255)                            not null,
    d4j_bug_id          integer                                 not null,
    model               varchar(255)                            not null,
    reasoning_level     varchar(255),
    max_fix_reprompts   integer                                 not null,
    feedback_iterations integer                                 not null,
    error_stack_trace   text,
    success             boolean default false                   not null,
    created_at          timestamp                               not null,
    completed_at        timestamp,
    constraint pk_run primary key (id)
);

create table if not exists target
(
    id         bigint generated by default as identity not null,
    run_id     bigint                                  not null,
    class_name varchar(255)                            not null,
    constraint pk_target primary key (id)
);

-- foreign keys and indices
create index if not exists ix_feedback_loop_target_id on feedback_loop (target_id);
alter table feedback_loop
    add constraint if not exists fk_feedback_loop_target_id foreign key (target_id) references target (id) on delete restrict on update restrict;

create index if not exists ix_feedback_loop_iteration_feedback_loop_id on feedback_loop_iteration (feedback_loop_id);
alter table feedback_loop_iteration
    add constraint if not exists fk_feedback_loop_iteration_feedback_loop_id foreign key (feedback_loop_id) references feedback_loop (id) on delete restrict on update restrict;

create index if not exists ix_feedback_loop_iteration_iteration_id on feedback_loop_iteration (iteration_id);
alter table feedback_loop_iteration
    add constraint if not exists fk_feedback_loop_iteration_iteration_id foreign key (iteration_id) references iteration (id) on delete restrict on update restrict;

create index if not exists ix_fixer_stage_iteration_id on fixer_stage (iteration_id);
alter table fixer_stage
    add constraint if not exists fk_fixer_stage_iteration_id foreign key (iteration_id) references iteration (id) on delete restrict on update restrict;

alter table fixer_stage
    add constraint if not exists fk_fixer_stage_follow_up_prompt_id foreign key (follow_up_prompt_id) references prompt (id) on delete restrict on update restrict;

create index if not exists ix_iteration_target_id on iteration (target_id);
alter table iteration
    add constraint if not exists fk_iteration_target_id foreign key (target_id) references target (id) on delete restrict on update restrict;

create index if not exists ix_iteration_generation_prompt_id on iteration (generation_prompt_id);
alter table iteration
    add constraint if not exists fk_iteration_generation_prompt_id foreign key (generation_prompt_id) references prompt (id) on delete restrict on update restrict;

create index if not exists ix_iteration_evaluation_id on iteration (evaluation_id);
alter table iteration
    add constraint if not exists fk_iteration_evaluation_id foreign key (evaluation_id) references evaluation (id) on delete restrict on update restrict;

create index if not exists ix_prompt_message_prompt_id on prompt_message (prompt_id);
alter table prompt_message
    add constraint if not exists fk_prompt_message_prompt_id foreign key (prompt_id) references prompt (id) on delete restrict on update restrict;

create index if not exists ix_target_run_id on target (run_id);
alter table target
    add constraint if not exists fk_target_run_id foreign key (run_id) references run (id) on delete restrict on update restrict;


create alias if not exists format_duration_ms as
$$
String formatDurationMs(long ms) {
   long hours = ms / 3_600_000;
   ms %= 3_600_000;

   long minutes = ms / 60_000;
   ms %= 60_000;

   long seconds = ms / 1_000;
   long millis = ms % 1_000;

   return String.format("%d:%02d:%02d.%03d", hours, minutes, seconds, millis);
}
$$;


create table if not exists costs
(
    model                     varchar(255)  not null,
    input_cost_per_1m_tokens  decimal(6, 3) not null,
    output_cost_per_1m_tokens decimal(6, 3) not null,
    constraint pk_costs primary key (model)
);

-- in USD
merge into costs (model, input_cost_per_1m_tokens, output_cost_per_1m_tokens)
    values ('gpt-4.1-nano', .1, .4),
           ('gpt-4.1-nano-2025-04-14', .1, .4),
           ('gpt-5-nano', .05, .4),
           ('gpt-5-nano-2025-08-07', .05, .4),
           ('codex-mini-lastest', 1.5, 6),
           ('gpt-5.2-codex', 1.75, 14);
